### ISSUE TITLE
RH Contact in Ecofish Research ?

### ISSUE THREAD

**Issue by axi** [bcaradima/bcaradima.github.io#1]
Hello Bogdan, I just find out you're working at Ecofish Research in Calgary and I also would like to do that. In fact I recently applied to their [Senior PHP developper](https://ecofishresearch.bamboohr.com/careers/313) offer but didn't get any response. Would you have any tips or someone I should contact to prove I'm THE man for the job ?
I hope this doesn't look intrusive, wish you the best
Alexis

**Comment by bcaradima** [comment]
Hi Alexis,

The link you posted is 404, but I see there are similar senior PHP developer postings on the careers page. I would suggest writing to info@ecofishresearch.com to inquire about the status of your application.

Best,
Bogdan

**Comment by axi** [comment]
Thanks Bogdan :-)
